server:
  port: 18081
spring:
  application:
    name: web-api
  data:
    mongodb:
      database: webflux
      uri: mongodb://localhost:27017
eureka:
  client:
    service-url:
      zoneD01: http://127.0.0.1:8761/eureka/
    region: d01
