server:
  port: 8082

spring:
  application:
    name: ds-gateway-zuul

eureka:
  client:
    service-url:
      zoneD02: http://127.0.0.1:8761/eureka/
    region: d02

logging:
  level:
    com.neflix: DEBUG

hystrix:
  command:
    default:
      execution:
        timeout:
          enable:true
        isolation:
          thread:
            timeoutInMilliseconds:2

